spring:
  main:
    allow-bean-definition-overriding: true
  mail:
    default-encoding: UTF-8
    host: smtp.mailtrap.io
    username: 3709a43a308a4a
    password: afacf9e33d0b92
    port: 2525
    protocol: smtp
    test-connection: false
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            ssl:
              trust: smtp.mailtrap.io
springdoc:
  api-docs:
    path: /salom
  swagger-ui:
    path: /hi.html